# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/richardvanderburgh/picplusplus_ubuntu_latest:latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependencies with Conan
      run: |
        
        mkdir build
        conan profile detect
        conan install . --profile=buildUtils/linux_gcc_release --build=missing -of=build
        conan build . --build-folder=build

    - name: Test
      working-directory: build
      run: ctest