# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: conanio/gcc9

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependencies with Conan
      run: |
        
        mkdir ${{github.workspace}}/build
        conan install ${{github.workspace}} --profile=${{github.workspace}}/buildUtils/linux_gcc_release --build=missing -of=${{github.workspace}}/build
        conan build ${{github.workspace}} --build-folder ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
