name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    container: ghcr.io/richardvanderburgh/picplusplus_ubuntu_latest:latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Dependencies with Conan (Ubuntu)
      run: |
        mkdir build
        conan profile detect
        conan install . --profile=buildUtils/linux_gcc_release --build=missing -of=build
        conan build . -build-folder=build

    # - name: Test (Ubuntu)
    #   working-directory: build
    #   run: ctest

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Python and Conan (Windows)
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: pip install conan
    
    - name: Install Dependencies with Conan (Windows)
      run: |
        mkdir build
        conan profile detect 
        conan install . --profile=buildUtils/win_release --build=missing -of=build
        conan build . -build-folder=build

    # - name: Test (Windows)
    #   working-directory: build
    #   run: .\path\to\your\test\command