
name: Build and Test PIC++ on macOS
on:
  push:
    branches:
      - macCICD

jobs:
  macos-latest-build:
    runs-on: macos-11

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Get Conan
      uses: turtlebrowser/get-conan@v1.0

    - name: Conan version
      run: echo "${{ steps.conan.outputs.version }}"

    - name: Build
      run: |
        conan profile detect
        mkdir build
        cd build
        conan install .. --profile:build=../buildUtils/mac_debug --build=missing
        conan build ..

    - name: Test
      run: ./bin/PIC++Lib_Test

